#!/bin/bash

function add_line_to_file(){
    local line=$1
    local file=$2
    if grep -Fxq "$line" $file
    then
        echo "Line already exists in $file"
    else
        echo "$line" >> $file
    fi
}



function main(){

    # Copy config files to ~/.config from /usr/share/promptorium/conf
    for user in $(ls /home); do
        echo "Copying config files to ~/.config for user $user"
        mkdir -p /home/$user/.config/promptorium
        # Only copy config files if they don't exist

        if [ ! -f /home/$user/.config/promptorium/conf.json ]; then
            cp -r /usr/share/promptorium/conf/conf.json /home/$user/.config/promptorium/conf.json
        else
            echo "Config file already exists for user $user"
        fi

        if [ ! -f /home/$user/.config/promptorium/theme.json ]; then
            cp -r /usr/share/promptorium/conf/theme.json /home/$user/.config/promptorium/theme.json
        else
            echo "Theme file already exists for user $user"
        fi

        if [ ! -d /home/$user/.config/promptorium/presets ]; then
            mkdir -p /home/$user/.config/promptorium/presets
            cp -r /usr/share/promptorium/conf/presets/* /home/$user/.config/promptorium/presets
        else
            echo "Presets directory already exists for user $user"
        fi

        # Copy shell files
        cp -r /usr/share/promptorium/conf/shell /home/$user/.config/promptorium
        

        chown -R $user:$user /home/$user/.config/promptorium
        
        # Add shell files to user's .bashrc and .zshrc
        add_line_to_file "source ~/.config/promptorium/shell/promptorium.bash" /home/$user/.bashrc
        add_line_to_file "source ~/.config/promptorium/shell/promptorium.zsh" /home/$user/.zshrc

    done

}

main

