#!/bin/bash

function main(){
    for user_home in /home/*; do
        local user
        user=$(basename "$user_home")
    
        echo "Removing lines from .bashrc and .zshrc for user $user"
        sed -i '/source ~\/.config\/promptorium\/shell\/promptorium.bash/d' /home/$user/.bashrc
        sed -i '/source ~\/.config\/promptorium\/shell\/promptorium.zsh/d' /home/$user/.zshrc
    done
}

main