
name: Build and Release

permissions:
  packages: write
  contents: write

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'


    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Set PROMPTORIUM_VERSION
      run: echo "PROMPTORIUM_VERSION=$(git describe --abbrev=0 --tags)" | sed 's/v//g' >> $GITHUB_ENV
    
    - name: Build
      run: make build-deb

    - name: Create version file
      run: echo ${{ env.PROMPTORIUM_VERSION }} > ./build/deb/version
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ env.PROMPTORIUM_VERSION }}
        tag_name: v${{ env.PROMPTORIUM_VERSION }}
        draft: false
        prerelease: false
        body: "Release of version ${{ env.PROMPTORIUM_VERSION }}"

    - name: Upload amd64 asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/promptorium_${{ env.PROMPTORIUM_VERSION }}_linux_amd64
        asset_name: promptorium_${{ env.PROMPTORIUM_VERSION }}_linux_amd64
        asset_content_type: application/octet-stream

    - name: Upload amd64 deb asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/deb/promptorium_${{ env.PROMPTORIUM_VERSION }}-1_amd64.deb
        asset_name: promptorium_${{ env.PROMPTORIUM_VERSION }}-1_amd64.deb
        asset_content_type: application/octet-stream

    - name: Deploy through ssh
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "./build/deb/*.deb"
        TARGET: "/home/${{ secrets.REMOTE_USER }}/promptorium/build/deb/"

    - name: Copy version file
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "./build/deb/version"
        TARGET: "/home/${{ secrets.REMOTE_USER }}/promptorium/build/deb/"

    - name: Update apt repository
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          bash /home/${{ secrets.REMOTE_USER }}/promptorium/scripts/update-apt-repo.bash
